language: c++

services:
  - docker

before_install:
  - docker build . -t kraken

script:
  - cd $(TRAVIS_BUILD_DIR) && \
  docker run --rm -v $(pwd):$(pwd) \
  kraken sh -c "mkdir build && cd build && CC=gcc CXX=g++ cmake -G \"Ninja\" .. && cmake --build . && cmake --build . --target test"
