language: c++

services:
  - docker

before_install:
  - docker build . -t kraken

script:
  - docker run --rm kraken sh -c "mkdir -p $(pwd)/build && cd $(pwd)/build && CC=gcc CXX=g++ cmake -G \"Ninja\" .. && cmake --build . && cmake --build . --target test"
